version: "2"
services:
  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-13.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/local/dcm4chee-arc/ldap:/var/lib/ldap
      - /var/local/dcm4chee-arc/slapd.d:/etc/ldap/slapd.d
  db:
    image: dcm4che/postgres-dcm4chee:10.0-13
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/disks/orthanc-db/dcm4chee-arc/db:/var/lib/postgresql/data
  arc:
    image: dcm4che/dcm4chee-arc-psql:5.13.1
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "8080:8080"
#      - "8042:8080"
      - "8443:8443"
      - "9990:9990"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/disks/orthanc-db/dcm4chee-arc/wildfly:/opt/wildfly/standalone
      - /mnt/disks/orthanc-db/dcm4chee-arc/storage:/storage

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  viewer:
    image: isb-cgc/ohif-viewer:latest
    ports:
      - "3000:3000"
    links:
      - mongo
      - arc
    environment:
      - MONGO_URL=mongodb://mongo:27017/ohif
#    extra_hosts:
#      - "pacsIP:172.18.0.4"
    volumes:
      - /home/dvproc/ohif-viewer/dockersupport/app.json:/app/app.json
